[package]
name = "DAOFramework"
version = "1.0.0"
authors = []

[addresses]
dao_creator = "0x2c4260acda2e032d1cbd6c1cd15cad5c8d930e715ef5a2bfd0fe285cd66b4c11"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"

[dev-dependencies]
